import { useEffect, useState } from "react"
import { RotateCcw, Save, Settings } from "lucide-react"

import { AppHeader } from "@/app/AppHeader"
import { Button } from "@/components/ui/button"
import { PageContainer } from "@/components/layout/PageContainer"
import {
  CLAYKEEPER_LOGO,
  defaultBrandSettings,
  saveBrandSettings,
  type BrandSettings,
} from "@/lib/branding"
import {
  loadOrganizationSettings,
  resetOrganizationSettings,
  saveOrganizationSettings,
} from "@/lib/services/organizationSettings"

export function SettingsPage() {
  const [form, setForm] = useState<BrandSettings>(defaultBrandSettings)
  const [message, setMessage] = useState("")
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState("")

  useEffect(() => {
    let cancelled = false

    async function load() {
      setLoading(true)
      setError("")

      try {
        const settings = await loadOrganizationSettings()

        if (cancelled) return

        setForm(settings)
        saveBrandSettings(settings)
      } catch (caught) {
        if (cancelled) return

        setError(
          caught instanceof Error
            ? caught.message
            : "Organization settings could not be loaded.",
        )
      } finally {
        if (!cancelled) setLoading(false)
      }
    }

    void load()

    return () => {
      cancelled = true
    }
  }, [])

  function update<K extends keyof BrandSettings>(key: K, value: BrandSettings[K]) {
    setForm((current) => ({ ...current, [key]: value }))
    setMessage("")
  }

  async function save() {
    setSaving(true)
    setMessage("")
    setError("")

    try {
      const settings = await saveOrganizationSettings(form)
      setForm(settings)
      saveBrandSettings(settings)
      setMessage("Organization branding and report preferences were saved.")
    } catch (caught) {
      setError(
        caught instanceof Error
          ? caught.message
          : "Organization settings could not be saved.",
      )
    } finally {
      setSaving(false)
    }
  }

  async function reset() {
    setSaving(true)
    setMessage("")
    setError("")

    try {
      const settings = await resetOrganizationSettings()
      setForm(settings)
      saveBrandSettings(settings)
      setMessage("Settings were restored to the organization defaults.")
    } catch (caught) {
      setError(
        caught instanceof Error
          ? caught.message
          : "Organization settings could not be reset.",
      )
    } finally {
      setSaving(false)
    }
  }

  return (
    <div className="min-h-screen bg-slate-50/70">
      <AppHeader title="Settings" description="Configure organization branding and report preferences" />

      <PageContainer>
        <div className="grid gap-6 xl:grid-cols-[1fr_360px]">
          <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
            <div className="flex items-start gap-3">
              <div className="rounded-xl bg-emerald-100 p-2 text-emerald-700"><Settings className="h-5 w-5" /></div>
              <div>
                <h2 className="text-xl font-bold text-slate-950">Organization identity</h2>
                <p className="mt-1 text-sm text-slate-500">These values appear in the sidebar and official report headers.</p>
              </div>
            </div>

            <div className="mt-6 grid gap-5 md:grid-cols-2">
              <Field label="Organization name" value={form.organizationName} onChange={(value) => update("organizationName", value)} placeholder="Organization name" />
              <Field label="Support email" value={form.supportEmail} onChange={(value) => update("supportEmail", value)} placeholder="support@example.org" type="email" />
              <div className="md:col-span-2"><Field label="Report subtitle" value={form.reportSubtitle} onChange={(value) => update("reportSubtitle", value)} placeholder="Trap · Skeet · Sporting Clays" /></div>
              <div className="md:col-span-2"><Field label="Report footer" value={form.reportFooter} onChange={(value) => update("reportFooter", value)} placeholder="Official results generated by ClayKeeper" /></div>
            </div>

            {loading ? (
              <div className="mt-5 rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-600">
                Loading organization settings…
              </div>
            ) : null}

            {error ? (
              <div className="mt-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
                {error}
              </div>
            ) : null}

            {message ? (
              <div className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">
                {message}
              </div>
            ) : null}

            <div className="mt-6 flex flex-wrap gap-3">
              <Button
                onClick={() => void save()}
                disabled={loading || saving}
              >
                <Save className="mr-2 h-4 w-4" />
                {saving ? "Saving…" : "Save settings"}
              </Button>

              <Button
                variant="outline"
                onClick={() => void reset()}
                disabled={loading || saving}
              >
                <RotateCcw className="mr-2 h-4 w-4" />
                Restore defaults
              </Button>
            </div>
          </section>

          <aside className="rounded-2xl border border-slate-200 bg-slate-950 p-6 text-white shadow-sm">
            <p className="text-xs font-semibold uppercase tracking-[0.2em] text-emerald-400">Brand preview</p>
            <img src={CLAYKEEPER_LOGO} alt="ClayKeeper TMK" className="mx-auto mt-5 h-48 w-full object-contain" />
            <div className="mt-5 rounded-xl border border-white/10 bg-white/5 p-4">
              <p className="font-semibold">{form.organizationName || "Organization"}</p>
              <p className="mt-1 text-xs uppercase tracking-[0.16em] text-slate-400">{form.reportSubtitle || "Trap · Skeet · Sporting Clays"}</p>
              <p className="mt-4 text-xs text-slate-400">{form.reportFooter || "Official results generated by ClayKeeper"}</p>
            </div>
            <p className="mt-4 text-xs leading-5 text-slate-500">The finalized ClayKeeper TMK logo is built into this release and is used on login, navigation, print reports, and browser icons.</p>
          </aside>
        </div>
      </PageContainer>
    </div>
  )
}

function Field({ label, value, onChange, placeholder, type = "text" }: { label: string; value: string; onChange: (value: string) => void; placeholder: string; type?: string }) {
  return (
    <label className="block text-sm font-medium text-slate-700">
      {label}
      <input
        type={type}
        value={value}
        onChange={(event) => onChange(event.target.value)}
        placeholder={placeholder}
        className="mt-2 h-11 w-full rounded-lg border border-slate-300 bg-white px-3 text-slate-950 outline-none transition focus:border-emerald-500 focus:ring-4 focus:ring-emerald-100"
      />
    </label>
  )
}
