-- ============================================================
-- ORGANIZATION SETTINGS
-- Persistent organization-level application configuration.
-- ============================================================

create table if not exists public.organization_settings (
  organization_id uuid primary key
    references public.organizations(id)
    on delete cascade,

  display_name text,
  support_email text,

  report_subtitle text not null
    default 'Trap · Skeet · Sporting Clays',

  report_footer text not null
    default 'Official results generated by ClayKeeper',

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint organization_settings_display_name_not_blank
    check (
      display_name is null
      or length(trim(display_name)) > 0
    ),

  constraint organization_settings_report_subtitle_not_blank
    check (length(trim(report_subtitle)) > 0),

  constraint organization_settings_report_footer_not_blank
    check (length(trim(report_footer)) > 0)
);

comment on table public.organization_settings
is 'Persistent organization-level ClayKeeper settings and preferences.';

comment on column public.organization_settings.display_name
is 'Optional ClayKeeper display/report name override for the organization.';

comment on column public.organization_settings.support_email
is 'Organization support/contact email shown by ClayKeeper where applicable.';

create trigger organization_settings_set_updated_at
before update on public.organization_settings
for each row
execute function public.set_updated_at();


-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================

alter table public.organization_settings enable row level security;

create policy "Members can view organization settings"
on public.organization_settings
for select
to authenticated
using (
  (select public.is_organization_member(organization_id))
);

create policy "Organization owners and admins can create settings"
on public.organization_settings
for insert
to authenticated
with check (
  (select public.has_organization_role(
    organization_id,
    array['owner', 'admin']
  ))
);

create policy "Organization owners and admins can update settings"
on public.organization_settings
for update
to authenticated
using (
  (select public.has_organization_role(
    organization_id,
    array['owner', 'admin']
  ))
)
with check (
  (select public.has_organization_role(
    organization_id,
    array['owner', 'admin']
  ))
);

create policy "Organization owners and admins can delete settings"
on public.organization_settings
for delete
to authenticated
using (
  (select public.has_organization_role(
    organization_id,
    array['owner', 'admin']
  ))
);
