import { useEffect, useState } from "react"

export const APP_VERSION = "2.6.2"
export const CLAYKEEPER_LOGO = "/branding/claykeeper-logo.png"
export const CLAYKEEPER_ICON = "/branding/claykeeper-icon-192.png"
export const CYSSA_LOGO = "/branding/cyssa-logo.png"

export type BrandSettings = {
  organizationName: string
  reportSubtitle: string
  reportFooter: string
  supportEmail: string
}

const STORAGE_KEY = "claykeeper.brand-settings"
const EVENT_NAME = "claykeeper:brand-settings"

export const defaultBrandSettings: BrandSettings = {
  organizationName: "ClayKeeper",
  reportSubtitle: "Trap · Skeet · Sporting Clays",
  reportFooter: "Official results generated by ClayKeeper",
  supportEmail: "",
}

export function loadBrandSettings(): BrandSettings {
  if (typeof window === "undefined") return defaultBrandSettings

  try {
    const stored = window.localStorage.getItem(STORAGE_KEY)
    if (!stored) return defaultBrandSettings
    return { ...defaultBrandSettings, ...JSON.parse(stored) }
  } catch {
    return defaultBrandSettings
  }
}

export function saveBrandSettings(settings: BrandSettings) {
  window.localStorage.setItem(STORAGE_KEY, JSON.stringify(settings))
  window.dispatchEvent(new CustomEvent(EVENT_NAME, { detail: settings }))
}

export function resetBrandSettings() {
  window.localStorage.removeItem(STORAGE_KEY)
  window.dispatchEvent(new CustomEvent(EVENT_NAME, { detail: defaultBrandSettings }))
}

export function useBrandSettings() {
  const [settings, setSettings] = useState<BrandSettings>(() => loadBrandSettings())

  useEffect(() => {
    const update = () => setSettings(loadBrandSettings())
    const updateFromEvent = (event: Event) => {
      const customEvent = event as CustomEvent<BrandSettings>
      setSettings(customEvent.detail ?? loadBrandSettings())
    }

    window.addEventListener("storage", update)
    window.addEventListener(EVENT_NAME, updateFromEvent)
    return () => {
      window.removeEventListener("storage", update)
      window.removeEventListener(EVENT_NAME, updateFromEvent)
    }
  }, [])

  return settings
}
